### ISSUE TITLE
Password field in datasource

### ISSUE THREAD

**Issue by JorundMartinsen** [grafana/grizzly#184]
The documentation states that passwords are not retrieved for datasources, and I should provide the password manually.

After editing the secureJson.password field and applying, Grafana still doesn't show a password.
This could be an issue with grafana api, but when inspecting the network request, the api seems to be similar.

Any suggestions?

Grafana version: 8.1.2
Grizzly version: dev-v0.1.0-47-gc7b2395
`grr apply resources/datasources/datasource-aDgYk2Hnk.yaml`

My datasource yaml. Edited to keep my secrets secret :)
```yaml
apiVersion: grizzly.grafana.com/v1alpha1
kind: Datasource
metadata:
    name: aDgYk2Hnk
spec:
    access: proxy
    basicAuth: false
    basicAuthPassword: ""
    basicAuthUser: ""
    database: myDb
    id: 1
    isDefault: true
    jsonData:
        postgresVersion: 1200
        sslmode: require
        timescaledb: true
        tlsAuth: true
        tlsAuthWithCACert: true
        tlsConfigurationMethod: file-path
        tlsSkipVerify: false
    name: PostgreSQL
    orgId: 1
    readOnly: false
    secureJsonFields:
        password: myPass
    type: postgres
    typeLogoUrl: ""
    uid: aDgYk2Hnk
    url: localhost:5432
    user: myUser
    version: 13
    withCredentials: false
```
