### ISSUE TITLE
Support managing Orgs

### ISSUE THREAD

**Issue by sathieu** [grafana/grizzly#268]
Context :
My pull request to add [Provisioning: orgs](https://github.com/grafana/grafana/pull/78253#issuecomment-1815222389) to Grafana was refused. I was pointed to grizzly.

Features needed: ability to create Orgs from manifests

Proposed format:

```yaml
apiVersion: grizzly.grafana.com/v1alpha1
kind: Org
metadata:
    name: Org 1
```
