### ISSUE TITLE
Grizzly did not find expected key

### ISSUE THREAD

**Issue by asreich** [grafana/grizzly#341]
I updated to use Grizzly 0.3.1 after using 0.2.0 to sync dashboards from Grafana 7.1.1 to Grafana Cloud 10.3/4.x. 0.2.0 worked last December but 0.3.0 has Alert resources I'd like to add so I've updated.

I am getting an error I did not get last time:

```
grr apply -d resources -t "DashboardFolder/*" -t "Dashboard/*"
Flag --directory has been deprecated, now it is inferred from the operating system
FATA[0003] Error decoding resources/dashboards/MbJTL4Viz/dashboard-_F63xZIVz.yaml: yaml: line 21: did not find expected key
```

The lines in question:
```yaml
...
    links: []
    panels:
        - content: |4+
            # Service Status

            More operations info and useful links available here: [Service Operations](https://ourdomain.com/display/PS/Service+Operations)



          datasource: null
...
```

When I remove the 4+ it seems happy, but this 4+ was there last time I synced and it worked no problem. There is also a 4- out there which it's also breaking on. This is the first time I've seen numbers after a | in YAML before.

Please let me know if you need any more info from me.

EDIT: Seems like there's an `id` field and a `version` field that aren't present in 0.2.0
