### ISSUE TITLE
[Feature Request]: Escape multiline values of specific fields under dashboard yaml

### ISSUE THREAD

**Issue by mehmetozturk4705** [grafana/grizzly#463]
### Feature Request

Hello, 
We really appreciate the latest developments. It has been really much of a quality of life improvement lately. 

### Limitation
We have been using serve functionality quite a while, and it has been our go-to way of QA process of dashboards. When reviwing, one limitation we are experiencing is:
- When we save panel SQL or markdown description change, diff is quite hard to follow on both diff checkers (Gitlab and VSCode diff checker), because the yaml serializers saves the multiline strings as json value rather then escaped yaml value.
- As a workaround, the reviewer either reviews the changed SQL completely, or uses some in-shell tooling to manually do diff check. Possibly another workaround is using some tooling for pre-commit hook of the repo, but this seems not maintainable. 

### Context

As a context, I can provide samples below for sample diff check sources

Example below could be diffed very well because the content part is lined well, easier to check when there are changes in specific lines.

```yaml
         .....
          options:
            code:
                language: plaintext
                showLineNumbers: false
                showMiniMap: false
            content: |
                ## Great header
                A good release note can be here. 
                
                ### Great subheader
                Some text to put.
            mode: markdown
            .....
```

Example below is how Grizzly serve (saving functionality) behaves and it has way much friction when doing a diff check. 

```yaml
         .....
          options:
            code:
                language: plaintext
                showLineNumbers: false
                showMiniMap: false
            content: "## Great header\nA good release note can be here. \n\n### Great subheader\nSome text to put."
            mode: markdown
            .....
```

Save functionality has a similar behavior in `rawSQL` of panels.
