### ISSUE TITLE
[Bug]: AlertRuleGroup does not sync deleted rules

### ISSUE THREAD

**Issue by minhthong582000** [grafana/grizzly#472]
### Grizzly Version

v0.4.3

### Expected Behavior

When using `grizzly` to sync a Grafana `AlertRuleGroup`, it works fine on creation. However, when I delete any rules, the rules still remain visible in the UI, requiring manual deletion later. This process is not user-friendly and is a significant risks in production.

```yaml
apiVersion: grizzly.grafana.com/v1alpha1
kind: AlertRuleGroup
metadata:
  name: myrules.alerts
spec:
  folderUid: myrules
  interval: 180 # in seconds
  rules:
    - rule-1
    - rule-2 # For example I delete this rule
  title: alerts
```

### Actual Behavior

In the example YAML above, if I want to delete `rule-2`, after running grizzly apply, `rule-2` should be removed from the UI.

### Steps to Reproduce

1. Create a `AlertRuleGroup` with 2 or more rules

```yaml
apiVersion: grizzly.grafana.com/v1alpha1
kind: AlertRuleGroup
metadata:
  name: myalert.alerts
spec:
  folderUid: myalert
  interval: 180 # in seconds
  rules:
    - condition: B
      data:
        - datasourceUid: grafanacloud-demoinfra-prom
          model:
            datasource:
              type: prometheus
              uid: grafanacloud-demoinfra-prom
            editorMode: code
            expr: weather_temp_c{location="Vienna"}
            instant: true
            intervalMs: 1000
            legendFormat: __auto
            maxDataPoints: 43200
            range: false
            refId: A
          refId: A
          relativeTimeRange:
            from: 600
        - datasourceUid: __expr__
          model:
            conditions:
              - evaluator:
                  params:
                    - 30
                  type: gt
                operator:
                  type: and
                query:
                  params:
                    - C
                reducer:
                  params: []
                  type: last
                type: query
            datasource:
              type: __expr__
              uid: __expr__
            expression: A
            intervalMs: 1000
            maxDataPoints: 43200
            refId: B
            type: threshold
          refId: B
          relativeTimeRange:
            from: 600
      execErrState: Error
      folderUID: myalert
      for: 5m0s
      noDataState: NoData
      orgID: 1
      ruleGroup: alerts
      title: Temperature high - 1
      # uid: alerts
    - condition: B
      data:
        - datasourceUid: grafanacloud-demoinfra-prom
          model:
            datasource:
              type: prometheus
              uid: grafanacloud-demoinfra-prom
            editorMode: code
            expr: weather_temp_c{location="Vienna"}
            instant: true
            intervalMs: 1000
            legendFormat: __auto
            maxDataPoints: 43200
            range: false
            refId: A
          refId: A
          relativeTimeRange:
            from: 600
        - datasourceUid: __expr__
          model:
            conditions:
              - evaluator:
                  params:
                    - 30
                  type: gt
                operator:
                  type: and
                query:
                  params:
                    - C
                reducer:
                  params: []
                  type: last
                type: query
            datasource:
              type: __expr__
              uid: __expr__
            expression: A
            intervalMs: 1000
            maxDataPoints: 43200
            refId: B
            type: threshold
          refId: B
          relativeTimeRange:
            from: 600
      execErrState: Error
      folderUID: myalert
      for: 5m0s
      noDataState: NoData
      orgID: 1
      ruleGroup: alerts
      title: Temperature high - 2
      # uid: alerts
  title: alerts
```

2. Run `grizzly apply`

3. Delete one of the rule:

```yaml
apiVersion: grizzly.grafana.com/v1alpha1
kind: AlertRuleGroup
metadata:
  name: myalert.alerts
spec:
  folderUid: myalert
  interval: 180 # in seconds
  rules:
    - condition: B
      data:
        - datasourceUid: grafanacloud-demoinfra-prom
          model:
            datasource:
              type: prometheus
              uid: grafanacloud-demoinfra-prom
            editorMode: code
            expr: weather_temp_c{location="Vienna"}
            instant: true
            intervalMs: 1000
            legendFormat: __auto
            maxDataPoints: 43200
            range: false
            refId: A
          refId: A
          relativeTimeRange:
            from: 600
        - datasourceUid: __expr__
          model:
            conditions:
              - evaluator:
                  params:
                    - 30
                  type: gt
                operator:
                  type: and
                query:
                  params:
                    - C
                reducer:
                  params: []
                  type: last
                type: query
            datasource:
              type: __expr__
              uid: __expr__
            expression: A
            intervalMs: 1000
            maxDataPoints: 43200
            refId: B
            type: threshold
          refId: B
          relativeTimeRange:
            from: 600
      execErrState: Error
      folderUID: myalert
      for: 5m0s
      noDataState: NoData
      orgID: 1
      ruleGroup: alerts
      title: Temperature high - 1
      # uid: alerts
  title: alerts
```

4. Run `grizzly apply` again.

5. Check UI, rule `Temperature high - 2` is still exist.

### Possible solution

I wonder if this line is correct when updating a rule group, as leaving the rules empty prevents the rules from being deleted correctly. Removing these lines seems to resolve the problem, I've tested this locally

(https://github.com/grafana/grizzly/blob/main/pkg/grafana/alertgroup-handler.go#L264-L266)
