### ISSUE TITLE
[Bug]: Library Panels do not work on Grizzly Server

### ISSUE THREAD

**Issue by zzv2** [grafana/grizzly#493]
### Grizzly Version

0.4.7

### Expected Behavior

Library Panels should load when a dashboard that uses the library panel is opened on the Grizzly Server

### Actual Behavior

Dashboards with Library Panels show an error on Grizzly Server:
![Image](https://github.com/user-attachments/assets/ae300c63-bf3c-46fc-a9b3-eaad5c0bb2b3)

But when the same dashboard is loaded on Grafana, there is no error and the Library Panel works fine:
![Image](https://github.com/user-attachments/assets/b03b9107-ea2e-4363-8110-5ac9179f5c0e)

### Steps to Reproduce

1. In your grafana instance (I am running grafana version 11.1.3), create a test dashboard and test library panel in a folder (in my example `development`)
2. Use `grr pull ...` to pull the test dashboard and test library panel
3. You should see something like this:
grizzly/resources/library-elements/panel-ddxpvhpo1fpj4d.yaml:
```
apiVersion: grizzly.grafana.com/v1alpha1
kind: LibraryElement
metadata:
    name: ddxpvhpo1fpj4d
spec:
    folderId: 1
    folderUid: development
    kind: 1
    model:
        datasource:
            type: dashboard
            uid: -- Dashboard --
        description: ""
        gridPos:
            h: 8
            w: 12
            x: 0
            "y": 0
        id: 1
        libraryPanel:
            name: Test Library Panel
            uid: ddxpvhpo1fpj4d
        options:
            code:
                language: plaintext
                showLineNumbers: false
                showMiniMap: false
            content: |-
                # Title

                For markdown syntax help: [commonmark.org/help](https://commonmark.org/help/)
            mode: markdown
        pluginVersion: 11.1.3
        targets:
            - datasource:
                type: datasource
                uid: -- Dashboard --
              refId: A
        title: Panel Title
        type: text
    name: Test Library Panel
    orgId: 1
    type: text
    uid: ddxpvhpo1fpj4d
```
grizzly/resources/dashboards/development/dashboard-adxpvipktdvy8e.yaml:
```
apiVersion: grizzly.grafana.com/v1alpha1
kind: Dashboard
metadata:
    folder: development
    name: adxpvipktdvy8e
spec:
    annotations:
        list:
            - builtIn: 1
              datasource:
                type: grafana
                uid: -- Grafana --
              enable: true
              hide: true
              iconColor: rgba(0, 211, 255, 1)
              name: Annotations & Alerts
              type: dashboard
    editable: true
    fiscalYearStartMonth: 0
    graphTooltip: 0
    links: []
    panels:
        - gridPos:
            h: 8
            w: 12
            x: 0
            "y": 0
          id: 2
          libraryPanel:
            name: Test Library Panel
            uid: ddxpvhpo1fpj4d
          title: Panel Title
    schemaVersion: 39
    tags: []
    templating:
        list: []
    time:
        from: now-6h
        to: now
    timepicker: {}
    timezone: browser
    title: New dashboard
    uid: adxpvipktdvy8e
    weekStart: ""
```

Strange that the library panel works fine on Grafana just not the Grizzly Server.
