### ISSUE TITLE
[Bug]: Failed to manifest dashboard when modifying lib

### ISSUE THREAD

**Issue by wilfriedroset** [grafana/grizzly#555]
### Grizzly Version

0.6.1

### Expected Behavior

Dashboards manifestion works without error when any of the files in the watchList are modified.

### Actual Behavior

Users might want to create reusable lib. As such they will start grizzly and watch several path. This is similar to what is documented here https://grafana.github.io/grizzly/server/, this is also what is done in [grafonnet examples(https://github.com/grafana/grafonnet/tree/main/examples/redMethod). Depending on what you are work on, user could edit either the dashboard itself or the underlying reusable lib.
However when grizzly detect a change in the underlying lib the manifestion fails

```
➜  reproducer docker compose up
[+] Running 2/0
 ✔ Container grafana  Created                                                                                                                                                                            0.0s
 ✔ Container grizzly  Recreated                                                                                                                                                                          0.1s
Attaching to grafana, grizzly
grafana  | logger=plugins.registration t=2025-01-10T13:22:54.913338607Z level=error msg="Could not register plugin" pluginId=xychart error="plugin xychart is already registered"
grafana  | logger=plugins.initialization t=2025-01-10T13:22:54.913475793Z level=error msg="Could not initialize plugin" pluginId=xychart error="plugin xychart is already registered"
grizzly  | level=info msg="[watcher] Watching for changes"
grizzly  | Listening on http://localhost:8080/
grizzly  | level=error msg="[watcher] Error: parse error in '/mnt/dashboards/examples/redMethod/lib/redDashboard/main.libsonnet': RUNTIME ERROR: couldn't manifest function as JSON\n\tField \"addApplication\"\t\n\tDuring manifestation\t\n"
grizzly  | level=warning msg="[watcher] error: parse error in '/mnt/dashboards/examples/redMethod/lib/redDashboard/main.libsonnet': RUNTIME ERROR: couldn't manifest function as JSON\n\tField \"addApplication\"\t\n\tDuring manifestation\t\n"
grizzly  | level=error msg="[watcher] Error: parse error in '/mnt/dashboards/examples/redMethod/lib/redDashboard/main.libsonnet': RUNTIME ERROR: couldn't manifest function as JSON\n\tField \"addApplication\"\t\n\tDuring manifestation\t\n"
grizzly  | level=warning msg="[watcher] error: parse error in '/mnt/dashboards/examples/redMethod/lib/redDashboard/main.libsonnet': RUNTIME ERROR: couldn't manifest function as JSON\n\tField \"addApplication\"\t\n\tDuring manifestation\t\n"
```

In this case, user could workaround the error by restarting grizzly at each change but it is cumbersome and make the watch feature less usefull.

### Steps to Reproduce

1. git clone https://github.com/grafana/grafonnet /tmp/grafonnet
2. cd /tmp/grafonnet/examples/redMethod && jb init
3. start the stack as describe in the docker-compose below
4. Open grizzly on localhost:8080 (or equivalent)
5. Browse the dashboard
6. Modify /tmp/grafonnet/examples/redMethod/lib/redDashboard/main.libsonnet

```yaml
---
services:
  grafana:
    image: grafana/grafana:11.4.0
    container_name: grafana
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_LOG_LEVEL=warning
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/api/health"]
      interval: 5s
      retries: 5
      start_period: 1s
      timeout: 10s

  grizzly:
    image: grafana/grizzly:0.6.1
    container_name: grizzly
    volumes:
      # git clone https://github.com/grafana/grafonnet /tmp/grafonnet
      - /tmp/grafonnet:/mnt/dashboards
    ports:
      - 8080:8080
    command:
      - serve
      - -w
      - /mnt/dashboards/examples/redMethod/main.libsonnet
      - /mnt/dashboards/examples/redMethod
    environment:
      - GRAFANA_URL=http://grafana:3000
      - GRAFANA_USER=admin
      - GRAFANA_TOKEN=password
    depends_on:
      grafana:
        condition: service_healthy
        restart: true
```
