### ISSUE TITLE
[Feature Request]: Make docker image ready to be used with grr config import

### ISSUE THREAD

**Issue by Ekimik** [grafana/grizzly#577]
### Feature Request

I am testing Grizzly and using Docker image `grafana/grizzly:0.6.1`. I have created following `docker-compose.yml` file for local testing
```yaml
services:
  grafana:
    container_name: grafana
    image: grafana/grafana:11.4.0
    ports:
      - 3333:3000
    volumes:
      - ~/.dockervolumes/grafana:/var/lib/grafana
  grizzly:
    container_name: grizzly
    image: grafana/grizzly:0.6.1
    ports:
      - 8888:8080
    volumes:
      - ./:/var/project
    entrypoint:
      - sleep
    command:
      - infinity
    environment:
      GRAFANA_URL: http://grafana:3000
      GRAFANA_USER: ...
      GRAFANA_TOKEN: ...
    working_dir: /var/project
```
See env variables passed to grizzly container, which can be used to configure access to Grafana according [docs](https://grafana.github.io/grizzly/configuration/). Once I exec to grizzly container and want to use `grr config import`, I got error 
```
FATAL mkdir /root/.config/grizzly: no such file or directory 
```
It would be nice if container were ready to use immediately after start. For now to make import command work I have to run manually
```
$ mkdir /root/.config
```
