### ISSUE TITLE
[Bug]: Can't apply dashboard after creating a new folder

### ISSUE THREAD

**Issue by DerkieH** [grafana/grizzly#585]
### Grizzly Version

0.7.1

### Expected Behavior

Grizzly should create the dashboard folder and then create the dashboard in this folder.

### Actual Behavior

Grizzly creates the folder, but can't create the dashboard because this folder does not exist.

```
grr apply test/
Applying 2 resources
DashboardFolder.grizzlyfolder added
Dashboard.dashboard failed: cannot upload dashboard dashboard as folder grizzlyfolder not found
1 resource added, 1 resource failed
```

### Steps to Reproduce

Create a folder.yaml and a dashboard.yaml:

```
apiVersion: grizzly.grafana.com/v1alpha1
kind: DashboardFolder
metadata:
  name: grizzlyfolder
spec:
  title: test
```

```
apiVersion: grizzly.grafana.com/v1alpha1
kind: Dashboard
metadata:
  folder: grizzlyfolder
  name: dashboard
spec:
  schemaVersion: 17
  tags:
    - grizzly
  timezone: browser
  title: dashboard
  uid: dashboard
```

grr apply test/

get the following output:

```
grr apply test/
Applying 2 resources
DashboardFolder.grizzlyfolder added
Dashboard.dashboard failed: cannot upload dashboard dashboard as folder grizzlyfolder not found
1 resource added, 1 resource failed
```
