### ISSUE TITLE
Use Kubernetes style resources instead of hidden elements

### ISSUE THREAD

**Issue by malcolmholmes** [grafana/grizzly#89]
Grizzly was first created to work with Monitoring Mixins in which resources are assigned to hidden elements. Then, the thing that consumes the mixin converts these into something else that isn't hidden.

Grizzly started using these hidden elements because, well, it was what we had at the time. However, reaching inside a Jsonnet program and extracting hidden elements (elements that are not supposed to be visible outside) is an antipattern - it just isn't a good idea. It got us this far, but it isn't the right way, longer term.

In terms of how we should represent our resources, we already have a perfectly acceptable model: Kubernetes with its apiVersion/kind/etc. My proposal is that Grizzly move away from using hidden elements and towards consuming Kubernetes style resources. The author of the Jsonnet code will be responsible for converting the hidden elements into suitable JSON resources. There is already a [library that does this](https://github.com/grafana/jsonnet-libs/tree/master/grizzly), so the conversion should be negligible effort.

An example of a dashboard could be:

```
apiVersion: grizzly.grafana.com/v1alpha1
kind: Dashboard
metadata:
  name: my-dash
  folder: sample
Data: |
{
  uid: 'prod-overview',
  title: 'Production Overview',
  tags: ['templated'],
  timezone: 'browser',
  schemaVersion: 17,
}
```
And a Prometheus rule group:

```
apiVersion: grizzly.grafana.com/v1alpha1
kind: PrometheusRuleGroup
metadata:
  name: prometheus_alerts
spec:
    rules:
      - alert: PromScrapeFailed
        annotations:
            message: |
                {{ $labels.job }} in {{ $labels.cluster}} has failed scrapes for 15m.
        expr: up != 1
        for: 15m
        labels:
            severity: critical
```
